language: php
php:
- 7.2
services:
- mysql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client
dist: trusty
sudo: required
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- mysql -e 'create database homestead_test;'
- npm install
- npm run production
script:
- php artisan key:generate
- vendor/bin/phpunit
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: Kq4VaMSwhebLyoqsLmVbh7ZhdOAut/7fgHrPgj6c3sX0Sn2bz5lHI6AT9c50eNlq87LiPDvPpXt8Wa3GFadpqlRP3u9EwNA2N4PTQ70VJWQXw8geg1yRJnSGs972SZDZxTM37Sdod/I+sLgOYo0C5aYLp4egqme75mKXqo+oexoaj7uDcCZK1RhXuzlojG0+1SPA+d7ya+hoQOAKWMoiTMviw011nLgZFSze9wHhdsZx9sszcRpnv4Oj9GzBeN6qs8nIMPf0WS2TUNb6mt7SrwA4JwyMsjraYcuwzbMASJIkfYEtSY0dYeOU+gafMvT34SmHdHir32U2yJ43CsWIrtgBBu26BJodoXhV5qwxfQxIkPsbZFOThoyDX5FSHaIDlohxUfAzWo5qs3TwIkPhCSNCCmQizbH9rlBFtDLhSWZIr9LB2c5ILxNvnOpQDaJziVSkicSJMbDD0uL+5qWi+rNH1N+rMpZwRM3BxmKfT/OfF5gormvKDnfzttGl5VebZ/UI5TB8MI419pAzi3UrmT2fJnyWum7p/17W/prmkUmjF/2M4M37T7+rIg80QOzBnnkpCSsjKGAV4s+3l7608Grxdi9MBg9+IyIqCgSqogZoyWrOuLmwY5OXIai6So+NmA46lf0kbeCJhjuCp1RIKdqN6zTviuJICbxwQ+o0aDE=
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.npm"
env:
  global:
  - secure: BS68PbWR/7wFwFHxZKL2tFN3PiyeoHKeyyKjMvuaZBILZXq5g0hntGmKtqze84Obq3+BT9dx8zXOpWiYV9af9S5K2lYe5ui/gg+gtdpFreeJOLyI4O7hZhbxOKmQAVU4iTZgEyCt1rbitfG/GxkiH/w5TYrkG+0GpURFBGGRuSLubGsEfPpm08z2A4JizkEksr6fYw59j1seLmicc4w05sP0pUYRsURUhOe1zvGJHGhmQ1xPkL2+g9hA5kig1jBGwgkGaHgmqwP3K+5+8P362LEr1HRZpnvxu51MZLtMGF/GdI6gFkMq980kbeDghM6e1CvFpyscvprGNfTDWMz+vgCxLtRo0/H0a2eQEzaLMwl9LO9DgJyaam2RSLBdavsl0uazVakj4l3/7zF/ZvSkNEYwLZPZUfSQaMgxLQ58Og4zdDTwn0CVTRJU9E33FCzK5IrFCgwsWpKmvk+fFQWKJFAyynEsdlzYv4bnSD/kfJCxMqqEimRquhmXzApKfbXK62oX0UlotdSmZYn3STrNyPHo1LrE6jIIlvdEFhKrkW5/nGrRcwdmUa0BwOFyyoG10sGydjE8gHmXngkylrb0Xrwym3WhshmLTVc5lh9o9Ym4xhkSSB5ufRxOmrK9Sm7yseSDTl3SK7tkqFkut9M6e32Q45UbSAtZUyMxA+NIQl8=
