version: '2'
services:
  nginx:
    build: ./containers/nginx/
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - app
    networks:
      - appnet

  php:
    build: ./containers/php/
    expose:
      - 9000
    volumes_from:
      - app
    networks:
      - appnet

  app:
    image: php:5.6-fpm
    volumes:
      - .:/var/www/html

  composer:
      image: composer/composer
      volumes_from:
        - app
      working_dir: /var/www/html

networks:
  appnet:
    driver: "bridge"